chocolatey_update.py, syncthing-gtk.nuspec, tools/chocolateyInstall.ps1
Since there are two installers, the package selected would depend of
the order they were published. Used the light installer for Chocolatey
since it's better for the updates.
Also made .nuspec and installer .ps1 version independant.
=> Chocolatey: Don't use the full installer

syncthing_gtk/editordialog.py
in cases when the path contains non-ascii symbols this fixes a not-so-nice 'editor-all-greyed-out' bug for me.
=> a tiny fix to work with non-ascii folderpaths

app.glade, syncthing_gtk/__init__.py, syncthing_gtk/app.py, syncthing_gtk/statusicon.py, syncthing_gtk/tools.py
Fix for #73 
This code has been tested in several desktop environments (see the "compatibility table" in `syncthing_gtk/statusicon.py`).
I tried to minimize the amount of the desktop probing as far as possible, but some checks remain. By default the `gtk.StatusIcon()`-based back-end will be loaded and will then check whether GTK succeeded in embedding the icon (`.is_embedded()`). If it didn't work, the other backends are tried in order (AppIndicator, KDE4, Dummy on Unity; KDE4, AppIndicator, Dummy on non-Unity) until one of them initializes correctly. Note that the GTK back-end will always fail on Unity and KDE.
There also used to also be a Qt5-based back-end but it was very unstable and required several hacks to prevent it from crashing the application. (Somehow, after calling …
=> Added StatusNotifier backend for KDE 4 (and 5)

syncthing_gtk/statusicon.py
Fix crash when an expected stock icon is missing from the current GTK theme while a QT-based status icon backend is loaded (fixes #127)
Skip desktop compatibility checks when explicitly forcing the use of the GTK3 status icon by using the "SYNCTHING_STATUS_BACKEND=GTK3" environment setting.
=> Fix for issue #127

chocolatey_update.py, syncthing-gtk.nuspec
As @Ferk suggested by mail, we can use [the syncthing chocolatey package](https://chocolatey.org/packages/syncthing) as a dependency of the [the syncthing-gtk chocolatey package](https://chocolatey.org/packages/syncthing-gtk). That's cool, we wanted a `syncthing`package since #28.
So, here is a simple commit that add `syncthing` as a dependency to our chocolatey package, and update the minimum required version from [app.py](https://github.com/syncthing/syncthing-gtk/blob/master/syncthing_gtk/app.py) when updating it.
**However**, the actual syncthing package is stuck on 0.10, with 0.11 (which is the version required by syncthing-gtk) awaiting moderation. Even if fixed, this issue may happen again later in time, so I think it would be wise to wait for `syncthing` becoming a trusted …
=> Chocolatey: Use syncthing as a dependency

syncthing_gtk/uisettingsdialog.py
[Exherbo](http://exherbo.org/) uses a [filesystem layout](https://exherbo.org/docs/multiarch.txt) which separates libraries and binaries based on what CHOST they were compiled for. `/usr/lib`, on Exherbo, is just a symlink to whatever the host machine's correct lib folder would be, which would break if running `i686-pc-linux-gnu` compiled things on a `x86_64-pc-linux-gnu` host; `syncthing-gtk` would start looking for x86_64-pc-linux-gnu's Nautilus library, and wouldn't find it correctly if it were only compiled for i686-pc-linux-gnu.
=> Add prefix paths for Exherbo's filesystem layout

syncthing_gtk/daemonprocess.py
On systems with non-GNU coreutils, `nice` usually expects to have `-n %s` passed to it, as the way
to specify the priority desired, rather than `-%s` which doesn't work on some implementations.
=> daemonprocess: Use more compatible syntax for `nice`

syncthing_gtk/tools.py
This call on XP expands to `Local Settings/Application Data` but Syncthing is storing config in just `Application Data`.
Closes #238
=> Find Syncthing config correctly on XP

syncthing-gtk.desktop
introduce a missing semicolon from the "Categories" line in the desktop file. It is needed for freedesktop.org specification compliance
it fixes this desktop-file-validate error:
/usr/share/applications/syncthing-gtk.desktop: error: value "Network" for string list key "Categories" in group "Desktop Entry" does not have a semicolon (';') as trailing character
=> syncthing-gtk.desktop: add missing semicolon

syncthing_gtk/app.py
Due to changes in the PATH environment variable in commit 38e42c566225494e7ccd9d5c4a2044540c2ee2c3 explorer.exe can not be found.  Now using SystemRoot environment variable to create absolute path to explorer.exe
=> absolute path to explorer.exe for Windows

syncthing_gtk/app.py, syncthing_gtk/notifications.py
Two more instances where the Folder Label should be displayed if set. Note that the second commit requires translation updates.
I'm not quite sure how to test the sync complete callback, I can usually only trigger `cb_syncthing_item_updated`, so please test this again before merging!
=> Include Folder Label in notifications

syncthing_gtk/app.py
Now using [os.startfile](https://docs.python.org/3.5/library/os.html#os.startfile) to launch Windows Explorer directly.  No need to mess with getting absolute path to explorer.exe (which I botched in my previous pull request).
=> simpler fix for Windows Explorer

README.md
This fixes #345.
Requesting merge against `master` since this isn't a fix to any code or functionality, but just a github-visible README file. I am happy to move it into a branch if that's preferred.
I couldn't find contributing guidelines in the syncthing-gtk repo, but am guilty of not looking too hard; apologies if I broke any rules.
=> Fix broken link to "syncthing" in first line of README.md

syncthing-gtk.desktop
This trivial change partially addresses #371, though it's not a complete solution.
=> syncthing-gtk.desktop: Don't assume that syncthing-gtk is in /usr/bin.

syncthing_gtk/app.py
This PR adds the command-line option `--no-status-icon`. If this option is given, syncthing-gtk will not attempt to show a tray status icon, even if it is possible to show one.
This is equivalent to running `SYNCTHING_STATUS_BACKEND=Dummy syncthing-gtk`, but nicer.
This fixes #370.
=> Add command-line option --no-status-icon (fixes #370)

README.md
In order for the status icon to work correctly on Gnome Shell and/or Unity, there are two more dependencies that may need to be installed. This PR adds them to README.md.
In particular, having these dependencies installed will fix #289, #342, #343, and #369.
=> Add dependencies needed to make the status icon work on Gnome Shell or Unity

syncthing_gtk/watcher.py
This dramatically reduces battery life needed when using
inotify.  Fixes #285.
=> Switch to timeout_add_seconds for inotify polling

syncthing_gtk/deviceeditor.py
Previously, if you were to type, say, `tcp://1.2.3.4:22000,dynamic`, it would be saved as `tcp://1.2.3.4:22000,tcp://dynamic` which would break the behavior of dynamic.
This fixes the behavior by adding a check specifically for the `dynamic` value to ensure that it does not have `tcp://` prepended.
This improves upon the solution for issue #300
=> Fixed addresses not allowing dynamic alongside other options

setup.py
This allows easier installation of the software, e.g. with
pip install https+git:////github.com/syncthing/syncthing-gtk.git#egg=syncthing-gtk
=> setup.py: Added dependencies to install_requires

chocolatey_update.py
I have confirmed that this is usable with latest version.
=> chocolatey_update.py: make it work with latest release schema

syncthing_gtk/statusicon.py
It should call set_from_icon_name() instead of set_from_file(), otherwise it tries to set the icon from an invalid path.
=> Fix invisible tray icon

locale/de/LC_MESSAGES/syncthing-gtk.po
While using syncthing-gtk, I noticed this wording, which is not only wrong but also doesn't make any sense. At first I wasn't even sure what it would do. Hopefully my version is clearer.
=> Translation change / bad wording

syncthing_gtk/app.py, syncthing_gtk/daemon.py, syncthing_gtk/notifications.py
So, this is my try to improve the notification structure in Syncthing GTK.
This adds now actions to the notifications and counts the events folder-wise to have a meaningful "folder finished" message.
@kozec: I added some `TODO`s in the code, where I have to invoke some callbacks. Could you help me there? Currently, you can't invoke an action to ignore a specific folder.
Fixes #464
=> Improve desktop notifications

syncthing_gtk/app.py, syncthing_gtk/configuration.py, syncthing_gtk/daemon.py, syncthing_gtk/daemonprocess.py, syncthing_gtk/deviceeditor.py, syncthing_gtk/foldereditor.py, syncthing_gtk/iddialog.py, syncthing_gtk/nautilusplugin.py, syncthing_gtk/notifications.py, syncthing_gtk/stdownloader.py, syncthing_gtk/tools.py, syncthing_gtk/uisettingsdialog.py, syncthing_gtk/wizard.py
Python 3 syntax for things like Exception handling, numeric octal literals, and set literals is backported to Python 2.7, so we can use it without any problems.
Implicit tuple unpacking is not supported in Python 3, so instead we can just make the tuple unpacking explicit.
=> Use newer notation

scripts/syncthing-plugin-nemo.py
I assume it's a misspelling but I don't know if there's any other code that relies on this outside of this repo.
=> Fix nemo misspelling?

syncthing_gtk/app.py, syncthing_gtk/daemon.py, syncthing_gtk/iddialog.py, syncthing_gtk/tools.py, syncthing_gtk/uibuilder.py
These are very slightly more invasive than the previous set (but not enormously so), and as such deserve a bit more scrutiny.
But FWIW, I did a little testing on my machine and everything worked fine.
* Made all relative imports explicit
* In places where ```dict.keys()``` and ```dict.values()``` are used with list operations, wrap them with ```list()``` first
* In Python 3, ```dict.keys()``` and ```dict.values()``` behave just like ```xrange()```, or ```dict.iterkeys()```/```dict.itervalues()```.  Therefore, while iterating over them is exactly the same, if you want to do list operations with them, you have to convert them into lists first.
* Changed ```xrange()``` to ```range()```
* For small range sizes, the difference should be imperceptible
More detail in commit messages / comments.
=> More backwards-compatible Python 3 changes

build_windows.py, syncthing_gtk/aboutdialog.py, syncthing_gtk/configuration.py, syncthing_gtk/daemon.py, syncthing_gtk/infobox.py, syncthing_gtk/stdownloader.py, syncthing_gtk/tools.py, syncthing_gtk/uibuilder.py, syncthing_gtk/wizard.py
Python 2 documentation recommends against the usage of ```file()```, and Python 3 removes it entirely. ```open()``` can do everything ```file()``` can do and using it is identical apart from having a few extra features.
Also, it's usually recommended to use the context manager pattern when dealing with files to prevent resource leaks. If you don't close the files, they will stick around in the process' file descriptor table. When using a context manager, the file is closed at the end of the scope.Alternatively the files could just be closed manually but this is easier and cleaner.
=>  Replace usages of the file() builtin with open() 

syncthing_gtk/infobox.py, syncthing_gtk/tools.py
Python 2's division operator behaves differently depending on the type
of the operands. If both operands are integer types, it will perform an
'integer division', whereas if one or both operands are a floating point
type it will perform a 'true division'.
e.g. In Python 2:
5 / 2 == 2
5 / 2.0 == 2.5
In Python 3, the division operator always performs a 'true division',
and the result will always be a floating point type regardless of the
input types.
e.g. In Python 3:
5 / 2 == 2.5
5 / 2.0 == 2.5
Both Python 2 and Python 3 allow the // operator, which always performs
floor (integer) division.
e.g. For both Python 2 and Python 3:
5 // 2 == 2
5 // 2.0 == 2.0
In places where both the operands are/should be integers, let's use // instead
of /. In Python 2, it will behave the same for these …
=> Specify integer division explicitly

syncthing_gtk/app.py
Fixing https://github.com/syncthing/syncthing-gtk/issues/525
=> Fix: Folder names containing unencoded html entities are blank

syncthing_gtk/app.py, syncthing_gtk/infobox.py, syncthing_gtk/tools.py
This makes it more robust and properly implemented :)
Because I still got errors in the log even though it was not visible in the GUI.
```
Okt 29 23:39:41 ubuntu syncthing-gtk[3538]: Failed to set text '<span color="white" font_weight="bold" font_size="large">Memories/Persons & Pets</span>' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity - escape ampersand as &amp;
```
=> [TASK] Improve html entity encoding

locale/fr/LC_MESSAGES/syncthing-gtk.po
The french "démarrer" verb has only 2 "r".
=> Fix typo in french PO file

syncthing_gtk/notifications.py
After upgrade with libnotify(0.7.12-1 -> 0.8.0-1) yesterday, the syncthing-gtk can't launch.
Find the similiar problem from both
EndeavorOS forum [link](https://forum.endeavouros.com/t/system-config-printer-error-in-namespace-notify/29251)
Archlinux bbs [link](https://bbs.archlinux.org/viewtopic.php?id=278077)
change the gi require version from 0.7 -> 0.8 fixed the issue. 
PR Accept お願いします
=> Syncthing-gtk can't initiated with latest libnotify
